### ISSUE TITLE
Remove ember-rollup

### ISSUE THREAD

**Issue by TerminalStar** [willrax/ember-luxon#25]
When attempting to upgrade to ember-cli 2.18, we get an error at the build stage:
![screen shot 2018-01-18 at 17 42 31](https://user-images.githubusercontent.com/9343433/35112784-0685e734-fc77-11e7-8df5-84e773053c19.png)

The log file suggests rollup is the cause and removing ember-luxon results in a successful build.

**Comment by willrax** [comment]
Removed and re added in another way :+1:
