### ISSUE TITLE
Feature Request: Ember Data Transform

### ISSUE THREAD

**Issue by pichfl** [willrax/ember-luxon#5]
A feature that is not supported by ember-moment, but is available as additional addon. 

Ember Data has a `date` transform that deserializes ISO dates to native `Date()` objects. Having a similar transform that provides Luxon objects instead is highly desired as it makes sense to have any occurrence of calendrical data in one format (especially given the welcome deviations in Luxon).

Given that luxon has multiple data structures, this addon should provide a transform for any reasonable variant.

- [x] DateTime Local
- [x] DateTime UTC
- [ ] Duration
- [ ] Interval

**Comment by willrax** [comment]
As in https://github.com/willrax/ember-luxon/pull/6 we decided to move this in to a different addon.
