### ISSUE TITLE
Change Request: Consider providing luxon as direct import, maybe in additional addon

### ISSUE THREAD

**Issue by pichfl** [willrax/ember-luxon#7]
Ember-Moment and others allow you to import the library they shim by name, i.e. 

```js
import 'moment' from 'moment';
```

I think doing the same with this addon might be useful, comparing 

```js
import { DateTime } from 'ember-luxon/luxon'; 
// vs
import { DateTime } from 'luxon'; 
```

The current option, while it safeguards against namespace collisions feels rather unnatural given that Luxon is provided as a ES6 module and uses the latter option in their own documentation.

**Comment by willrax** [comment]
Interesting. We find that our new developers find `import moment from 'moment';` a bit confusing because it's uncertain where it's coming from.

Perhaps `import { DateTime } from 'ember-luxon';`?

**Comment by willrax** [comment]
I can picture a future where this type of wrapper isn't needed and you can import directly from npm. At that point it would be fairly easy for a dev to change the import to their own  npm luxon version.

Let me know what you think.

**Comment by pichfl** [comment]
I suppose that would work as well, but it would require this addon to follow a rather strict release cycle including deprecations etc. 

In the best case for me we'll arrive at some point in the future where you simply drop `ember-luxon` from the dependencies and replace it by `luxon` without ever adjusting your code. 

Maybe we should consider following https://github.com/jasonmit/ember-cli-moment-shim here and release the shim separately. This would give us the option to provide the expected imports (as the shim would be a dependency of ember-luxon only to work around the fact we can not use nom modules directly for now) and leave space for this addon to provide the helpers etc.

**Comment by willrax** [comment]
Oh thats not a bad idea. In the meantime, we can switch the import to be `luxon` directly and drop the `ember-luxon` name space. You're point about the dropping of the import all together when we can consume npm directly makes perfect sense.

**Comment by willrax** [comment]
Here is the PR https://github.com/willrax/ember-luxon/pull/8

**Comment by willrax** [comment]
Was able to deprecate the use of the import here: https://github.com/willrax/ember-luxon/commit/7827987bdc6723b89bbcb4a9ed9f9e385a049795 without needing to completely remove it.
